import React from 'react';
import { Recommendation } from '../types';
import { recommendations as defaultRecommendations } from '../data/mockData';
import { 
  AlertOctagon, 
  AlertTriangle, 
  CheckCircle2, 
  Sparkles, 
  Layers, 
  Zap, 
  Target, 
  ShieldCheck, 
  Check, 
  X,
  TrendingUp 
} from 'lucide-react';

interface AiInsightsCardsProps {
  recommendations?: Recommendation[];
}

export const AiInsightsCards: React.FC<AiInsightsCardsProps> = ({ recommendations = defaultRecommendations }) => {
  const getRecIcon = (type: Recommendation['type']) => {
    switch (type) {
      case 'critical':
        return <AlertOctagon className="w-5 h-5 text-rose-600" />;
      case 'warning':
        return <AlertTriangle className="w-5 h-5 text-amber-600" />;
      case 'success':
        return <CheckCircle2 className="w-5 h-5 text-emerald-600" />;
    }
  };

  const getRecBadge = (type: Recommendation['type']) => {
    switch (type) {
      case 'critical':
        return <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-rose-100 text-rose-800 border border-rose-200">High Priority</span>;
      case 'warning':
        return <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-amber-100 text-amber-800 border border-amber-200">Suggested</span>;
      case 'success':
        return <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 border border-emerald-200 font-semibold">Passed</span>;
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      
      {/* Card 1: AI Fix Recommendations */}
      <div className="lg:col-span-2 bg-white rounded-2xl border border-slate-200 shadow-2xs p-5 sm:p-6 space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-50 text-[#1877f2] flex items-center justify-center font-bold">
              <Zap className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-[#0F172A]">
                AI Optimization Feedback & Action Items
              </h3>
              <p className="text-xs text-[#64748B]">
                Prioritized recommendations generated by deep neural parse checks.
              </p>
            </div>
          </div>
          <span className="text-xs font-bold text-[#1877f2] flex items-center gap-1 bg-blue-50 px-2.5 py-1 rounded-lg">
            <Sparkles className="w-3.5 h-3.5 text-[#1877f2]" /> 3 Insights
          </span>
        </div>

        <div className="space-y-3">
          {(recommendations || []).map((rec) => (
            <div
              key={rec.id}
              className={`p-4 rounded-xl border transition-all ${
                rec.type === 'critical'
                  ? 'bg-rose-50/40 border-rose-200/80 hover:bg-rose-50'
                  : rec.type === 'warning'
                  ? 'bg-amber-50/40 border-amber-200/80 hover:bg-amber-50'
                  : 'bg-emerald-50/40 border-emerald-200/80 hover:bg-emerald-50'
              }`}
            >
              <div className="flex items-start justify-between gap-3 mb-1.5">
                <div className="flex items-center gap-2">
                  {getRecIcon(rec.type)}
                  <h4 className="text-xs font-bold text-[#0F172A]">{rec.title}</h4>
                </div>
                {getRecBadge(rec.type)}
              </div>
              
              <p className="text-xs text-[#64748B] leading-relaxed mb-2.5 pl-7">
                {rec.description}
              </p>

              <div className="pl-7 flex items-center justify-between">
                <span className="text-[11px] font-extrabold text-blue-700 bg-blue-100/70 px-2 py-0.5 rounded-md flex items-center gap-1">
                  <TrendingUp className="w-3 h-3 text-[#1877f2]" /> {rec.impact}
                </span>
                <button className="text-xs font-bold text-[#1877f2] hover:underline cursor-pointer">
                  Auto-Fix with AI →
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Card 2: Skill Compatibility Matrix */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xs p-5 sm:p-6 space-y-4 flex flex-col justify-between">
        <div>
          <div className="flex items-center gap-2.5 pb-3 border-b border-slate-100">
            <div className="w-8 h-8 rounded-lg bg-blue-50 text-[#1877f2] flex items-center justify-center font-bold">
              <Target className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-[#0F172A]">Keyword Match Analysis</h3>
              <p className="text-xs text-[#64748B]">Requirements vs Resume</p>
            </div>
          </div>

          <div className="mt-4 space-y-3">
            <div>
              <div className="flex justify-between text-xs font-bold text-[#0F172A] mb-1">
                <span>Matched Required Skills (8/10)</span>
                <span className="text-emerald-600">80%</span>
              </div>
              <div className="flex flex-wrap gap-1.5 mt-2">
                {['React.js', 'TypeScript', 'Tailwind', 'Node.js', 'REST APIs', 'Jest', 'Git'].map((s) => (
                  <span
                    key={s}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold bg-emerald-50 text-emerald-800 border border-emerald-200"
                  >
                    <Check className="w-3 h-3 text-emerald-600" /> {s}
                  </span>
                ))}
              </div>
            </div>

            <div className="pt-2">
              <div className="flex justify-between text-xs font-bold text-[#0F172A] mb-1">
                <span>Missing Key Terms (2)</span>
                <span className="text-rose-600">Action Needed</span>
              </div>
              <div className="flex flex-wrap gap-1.5 mt-2">
                {['GraphQL', 'CI/CD Pipelines'].map((s) => (
                  <span
                    key={s}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-semibold bg-rose-50 text-rose-800 border border-rose-200"
                  >
                    <X className="w-3 h-3 text-rose-600" /> {s}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* ATS Format Check Banner */}
        <div className="p-3.5 bg-blue-50/70 border border-blue-200/80 rounded-xl space-y-1">
          <div className="flex items-center gap-2 text-xs font-bold text-[#0F172A]">
            <ShieldCheck className="w-4 h-4 text-[#1877f2]" />
            <span>Parser Compatibility: Passed</span>
          </div>
          <p className="text-[11px] text-[#64748B] leading-tight">
            Font encoding, section headers, and standard date formats match Workday & Greenhouse parser requirements.
          </p>
        </div>

      </div>

    </div>
  );
};
