import React from 'react';
import { motion } from 'motion/react';
import { Recommendation } from '../types';
import { recommendations as defaultRecommendations } from '../data/mockData';
import { 
  AlertOctagon, 
  AlertTriangle, 
  CheckCircle2, 
  Sparkles, 
  Zap, 
  Target, 
  ShieldCheck, 
  Check, 
  X,
  TrendingUp 
} from 'lucide-react';

interface AiInsightsCardsProps {
  recommendations?: Recommendation[];
}

export const AiInsightsCards: React.FC<AiInsightsCardsProps> = ({ recommendations = defaultRecommendations }) => {
  const getRecIcon = (type: Recommendation['type']) => {
    switch (type) {
      case 'critical':
        return <AlertOctagon className="w-5 h-5 text-[#FF6B6B]" />;
      case 'warning':
        return <AlertTriangle className="w-5 h-5 text-amber-500" />;
      case 'success':
        return <CheckCircle2 className="w-5 h-5 text-[#1F2937]" />;
    }
  };

  const getRecBadge = (type: Recommendation['type']) => {
    switch (type) {
      case 'critical':
        return <span className="text-[10px] font-black px-2.5 py-0.5 rounded-full bg-rose-50 text-[#FF6B6B] border border-rose-200">High Priority</span>;
      case 'warning':
        return <span className="text-[10px] font-black px-2.5 py-0.5 rounded-full bg-amber-50 text-amber-700 border border-amber-200">Suggested</span>;
      case 'success':
        return <span className="text-[10px] font-black px-2.5 py-0.5 rounded-full bg-[#7EDCC3]/20 text-[#1F2937] border border-[#7EDCC3]/30">Passed</span>;
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      
      {/* Card 1: AI Fix Recommendations */}
      <motion.div 
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="lg:col-span-2 bg-white rounded-[20px] border border-[#EEF2F7] soft-shadow p-5 sm:p-6 space-y-4"
      >
        <div className="flex items-center justify-between pb-3 border-b border-[#EEF2F7]">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-[#4F7CFF]/10 text-[#4F7CFF] flex items-center justify-center font-bold">
              <Zap className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-black text-[#1F2937]">
                AI Optimization Feedback & Action Items
              </h3>
              <p className="text-xs text-[#6B7280] font-medium">
                Prioritized recommendations generated by deep neural parse checks.
              </p>
            </div>
          </div>
          <span className="text-xs font-black text-[#4F7CFF] flex items-center gap-1 bg-[#4F7CFF]/10 px-3 py-1 rounded-full border border-[#4F7CFF]/20">
            <Sparkles className="w-3.5 h-3.5 text-[#4F7CFF]" /> 3 Insights
          </span>
        </div>

        <div className="space-y-3">
          {(recommendations || []).map((rec, idx) => (
            <motion.div
              key={rec.id}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.25, delay: idx * 0.08 }}
              className={`p-4 rounded-2xl border transition-all ${
                rec.type === 'critical'
                  ? 'bg-rose-50/40 border-rose-200/80 hover:bg-rose-50'
                  : rec.type === 'warning'
                  ? 'bg-amber-50/40 border-amber-200/80 hover:bg-amber-50'
                  : 'bg-[#7EDCC3]/10 border-[#7EDCC3]/30 hover:bg-[#7EDCC3]/20'
              }`}
            >
              <div className="flex items-start justify-between gap-3 mb-1.5">
                <div className="flex items-center gap-2">
                  {getRecIcon(rec.type)}
                  <h4 className="text-xs font-black text-[#1F2937]">{rec.title}</h4>
                </div>
                {getRecBadge(rec.type)}
              </div>
              
              <p className="text-xs text-[#6B7280] leading-relaxed mb-2.5 pl-7 font-medium">
                {rec.description}
              </p>

              <div className="pl-7 flex items-center justify-between">
                <span className="text-[11px] font-black text-[#4F7CFF] bg-[#4F7CFF]/10 px-2.5 py-0.5 rounded-full flex items-center gap-1">
                  <TrendingUp className="w-3 h-3 text-[#4F7CFF]" /> {rec.impact}
                </span>
                <button className="text-xs font-extrabold text-[#4F7CFF] hover:underline cursor-pointer">
                  Auto-Fix with AI →
                </button>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Card 2: Skill Compatibility Matrix */}
      <motion.div 
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: 0.1 }}
        className="bg-white rounded-[20px] border border-[#EEF2F7] soft-shadow p-5 sm:p-6 space-y-4 flex flex-col justify-between"
      >
        <div>
          <div className="flex items-center gap-2.5 pb-3 border-b border-[#EEF2F7]">
            <div className="w-8 h-8 rounded-xl bg-[#4F7CFF]/10 text-[#4F7CFF] flex items-center justify-center font-bold">
              <Target className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-black text-[#1F2937]">Keyword Match Analysis</h3>
              <p className="text-xs text-[#6B7280] font-medium">Requirements vs Resume</p>
            </div>
          </div>

          <div className="mt-4 space-y-3">
            <div>
              <div className="flex justify-between text-xs font-black text-[#1F2937] mb-1">
                <span>Matched Required Skills (8/10)</span>
                <span className="text-[#4F7CFF]">80%</span>
              </div>
              <div className="flex flex-wrap gap-1.5 mt-2">
                {['React.js', 'TypeScript', 'Tailwind', 'Node.js', 'REST APIs', 'Jest', 'Git'].map((s) => (
                  <span
                    key={s}
                    className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-extrabold bg-[#7EDCC3]/20 text-[#1F2937] border border-[#7EDCC3]/30"
                  >
                    <Check className="w-3 h-3 text-[#1F2937]" /> {s}
                  </span>
                ))}
              </div>
            </div>

            <div className="pt-2">
              <div className="flex justify-between text-xs font-black text-[#1F2937] mb-1">
                <span>Missing Key Terms (2)</span>
                <span className="text-[#FF6B6B]">Action Needed</span>
              </div>
              <div className="flex flex-wrap gap-1.5 mt-2">
                {['GraphQL', 'CI/CD Pipelines'].map((s) => (
                  <span
                    key={s}
                    className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-extrabold bg-rose-50 text-[#FF6B6B] border border-rose-200"
                  >
                    <X className="w-3 h-3 text-[#FF6B6B]" /> {s}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* ATS Format Check Banner */}
        <div className="p-3.5 bg-[#4F7CFF]/5 border border-[#EEF2F7] rounded-2xl space-y-1">
          <div className="flex items-center gap-2 text-xs font-black text-[#1F2937]">
            <ShieldCheck className="w-4 h-4 text-[#4F7CFF]" />
            <span>Parser Compliance: Passed</span>
          </div>
          <p className="text-[11px] text-[#6B7280] font-medium leading-tight">
            Font encoding, section headers, and standard date formats match Workday & Greenhouse parser requirements.
          </p>
        </div>

      </motion.div>

    </div>
  );
};
