import { Router } from 'express';
import multer from 'multer';
import {
  uploadResume,
  analyzeResumeById,
  analyzeResumeDirect,
  getResumes,
  getResumeById,
  getResumeResult,
  getAISuggestions,
  deleteResume,
  chatResume,
} from '../controllers/resumeController.js';

const router = Router();

// Configure multer for in-memory file handling
const storage = multer.memoryStorage();

const fileFilter = (
  _req: any,
  file: Express.Multer.File,
  cb: multer.FileFilterCallback
) => {
  const originalName = (file.originalname || '').toLowerCase();
  const mime = (file.mimetype || '').toLowerCase();

  const isPdf = originalName.endsWith('.pdf') || mime.includes('pdf');
  const isDocx =
    originalName.endsWith('.docx') ||
    mime.includes('wordprocessingml') ||
    mime.includes('openxmlformats') ||
    mime.includes('vnd.openxmlformats-officedocument.wordprocessingml.document');
  const isDoc = originalName.endsWith('.doc') || mime.includes('msword') || mime.includes('document');
  const isTxt = originalName.endsWith('.txt') || originalName.endsWith('.md') || mime.includes('text/');
  const isGeneric = mime === 'application/octet-stream' || mime === 'binary/octet-stream';

  if (isPdf || isDocx || isDoc || isTxt || isGeneric) {
    cb(null, true);
  } else {
    cb(new Error('Supported resume formats: PDF (.pdf), Word (.docx, .doc), or Text (.txt). Please upload a valid document.'));
  }
};

const upload = multer({
  storage,
  fileFilter,
  limits: {
    fileSize: 20 * 1024 * 1024, // 20MB limit
  },
});

// Flexible upload middleware supporting single 'resume', 'file', 'document', or any field
const uploadMiddleware = upload.any();

/**
 * POST /upload
 * Upload PDF or DOCX and create initial record with status 'uploaded'
 */
router.post('/upload', uploadMiddleware, uploadResume);

/**
 * POST /analyze/:resumeId
 * Workflow: Find uploaded resume by ID -> extract PDF/DOCX -> Gemini AI analysis -> save to DB -> return status & analysis
 */
router.post('/analyze/:resumeId', uploadMiddleware, analyzeResumeById);

/**
 * POST /analyze
 * Combined 1-step upload + extract + Gemini analyze
 */
router.post('/analyze', uploadMiddleware, analyzeResumeDirect);

/**
 * GET /result/:resumeId
 * Get structured analysis result by resume ID
 */
router.get('/result/:resumeId', getResumeResult);

/**
 * GET /suggestions/:resumeId
 * Get personalized AI suggestions generated by Gemini API
 */
router.get('/suggestions/:resumeId', getAISuggestions);

/**
 * POST /chat
 * Interactive chat with Gemini AI about a selected resume
 */
router.post('/chat', chatResume);

/**
 * GET /
 * Get all resumes
 */
router.get('/', getResumes);

/**
 * GET /:id
 * Get resume by ID
 */
router.get('/:id', getResumeById);

/**
 * DELETE /:id
 * Delete resume record
 */
router.delete('/:id', deleteResume);

export default router;
