import { Router } from 'express';
import multer from 'multer';
import {
  uploadResume,
  analyzeResumeById,
  analyzeResumeDirect,
  getResumes,
  getResumeById,
  getResumeResult,
  getAISuggestions,
  deleteResume,
  chatResume,
} from '../controllers/resumeController.js';

const router = Router();

// Configure multer for in-memory file handling
const storage = multer.memoryStorage();

const fileFilter = (
  _req: any,
  file: Express.Multer.File,
  cb: multer.FileFilterCallback
) => {
  if (
    file.mimetype === 'application/pdf' ||
    file.originalname.toLowerCase().endsWith('.pdf')
  ) {
    cb(null, true);
  } else {
    cb(new Error('Only PDF documents (.pdf) are allowed for resume analysis!'));
  }
};

const upload = multer({
  storage,
  fileFilter,
  limits: {
    fileSize: 10 * 1024 * 1024, // 10MB limit
  },
});

/**
 * POST /upload
 * Upload PDF and create initial record with status 'uploaded'
 */
router.post('/upload', upload.single('resume'), uploadResume);

/**
 * POST /analyze/:resumeId
 * Workflow: Find uploaded resume by ID -> extract PDF -> Gemini AI analysis -> save to DB -> return status & analysis
 */
router.post('/analyze/:resumeId', upload.single('resume'), analyzeResumeById);

/**
 * POST /analyze
 * Combined 1-step upload + extract + Gemini analyze
 */
router.post('/analyze', upload.single('resume'), analyzeResumeDirect);

/**
 * GET /result/:resumeId
 * Get structured analysis result by resume ID
 */
router.get('/result/:resumeId', getResumeResult);

/**
 * GET /suggestions/:resumeId
 * Get personalized AI suggestions generated by Gemini API
 */
router.get('/suggestions/:resumeId', getAISuggestions);

/**
 * POST /chat
 * Interactive chat with Gemini AI about a selected resume
 */
router.post('/chat', chatResume);

/**
 * GET /
 * Get all resumes
 */
router.get('/', getResumes);

/**
 * GET /:id
 * Get resume by ID
 */
router.get('/:id', getResumeById);

/**
 * DELETE /:id
 * Delete resume record
 */
router.delete('/:id', deleteResume);

export default router;
